image: ghcr.io/uwacsds/citsbot

environment: prod

pushgatewayUrl: http://prometheus-pushgateway.metrics:9091

secrets:
  - name: citsbot.config.prod
    ref: prod/cluster/json
    properties:
      - name: token
        key: projects.citsbot.prod.token
      - name: config
        key: projects.citsbot.prod.config
