{{- range $i, $secret := .Values.secrets -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ $secret.name }}"
spec:
  backendType: secretsManager
  data:
    {{ if $secret.property }}
    - key: "{{ $secret.ref }}"
      name: "{{ $secret.property }}"
    {{ else }}
      {{ range $j, $property := $secret.properties }}
      - key: "{{ $secret.ref }}"
        name: "{{ $property.name }}"
        property: "{{ $property.key }}"
      {{ end }}
    {{ end }}
---
{{- end }}
