name: Deploy

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          target: prod
